### ISSUE TITLE
EIP creation and usage

### ISSUE THREAD

**Issue by keyvaann** [RADAR-base/RADAR-K8s-Infrastructure#33]
Looking at the `config/eip.tf` I see that an EIP is created, and it's referenced in the `route53` configuration, but I can't seem to figure out how it's attached to the cluster since there is no mention of a network interface in the `eip.tf` file. 
I'm also not sure why this allocation is needed, since the VPC module in the `cluster` directory already creates an EIP for the cluster.

**Comment by baixiac** [comment]
The EIP created by the VPC module is for the NAT gateway. The EIP created in `config/eip.tf` is for the NLB, dynamically utilised by the nginx-ingress controller. E.g., in `production.yaml` users can configure:

```
nginx_ingress:
    _install: true
    controller:
        ...
        service:
            annotations:
                service.beta.kubernetes.io/aws-load-balancer-type: nlb
                service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-XXXXXXXX
                service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-XXXXXXXX
```
